### PR TITLE
Bookstore: styling

### PR DESCRIPTION
**Pull request by sheylaPozo**
## Styling

- Add styling to the components.

Thank you for reviewing my PR! 🌈✨🎠😊

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @sheylaPozo 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome :heavy_check_mark:

Changes required :writing_hand: 

   - You have imported the wrong file in the App.js that makes your project not running. `Module not found: Can't resolve './components/Books/BooksPage'`

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @sheylaPozo 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome :heavy_check_mark:

Changes required :writing_hand: 

   - You have imported the wrong file in the App.js that makes your project not running. `Module not found: Can't resolve './components/Books/BooksPage'`

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by sheylaPozo** [comment]
Hello, my project does run, any time I do npm start or npm build, npm start it shows and the project works, besides the project requirement is styling, and my project is already been verified from functionality and all by previous TSEs, this was just to add colors and nothing else.

**Comment by sheylaPozo** [comment]
Hello, my project does run, any time I do "npm start" or "npm build, npm start" it shows and the project works, besides the project requirement is styling, and my project has already been verified from functionality and approved by all the previous TSEs, who reviewed it, and in this project, I didn't modify nothing on functionality aspects, only colors, this was just to add colors and nothing else.

**Comment by Emmyn5600** [comment]
Hello too, @sheylaPozo, you are importing `import BooksPage from './components/Books/BooksPage';  however, the folder is books not Books. please take a look:point_down:

style2

style3

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @sheylaPozo 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome :heavy_check_mark:

Changes required :writing_hand: 

   - You have imported the wrong file in the App.js that makes your project not running. `Module not found: Can't resolve './components/Books/BooksPage'` Please correct that you will get approved.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by sheylaPozo** [comment]
image
 I didn't modify anything and it runs normally on my end, look.

**Comment by Emmyn5600** [comment]
Please do check my comment.

**Comment by sheylaPozo** [comment]
> Please do check my comment.

image
Like I said, I didn't modify anything and in my end, it's Books in that part, it's never been other way around,  I didn't even commit any changes to the project-related books or Books.  look....I think that's just on your end, plus previous TSE reviewed me, ran my project and all.  And I haven't modify anything on that, maybe verify that you are looking at the last changes that are on styling branch.

**Comment by Emmyn5600** [comment]
You only have small issue to solve before you get approved. You only have to change Books to books in the App.js. Please try it, it won't affect your running project.

**Comment by sheylaPozo** [comment]
> You have only small issue to solve before you get approved. You only have to change Books to books in the App.js. Please try it, it won't affect your running project.

I think you're looking at the wrong branch, last branch "styling" has it as Books as you an check on the screenshot evidence.

**Comment by Emmyn5600** [comment]
Not, It's styling branch
syle

**Comment by sheylaPozo** [comment]
image
 mine also is styling branch and it says Books not books.

**Comment by sheylaPozo** [comment]
image
I believe if I can't see the error you're getting, on my end, I can't modify it, and it wouldn't be fair to be held from approval for that, if you want we can have a zoom call and I can show you my project, but it does work and I haven't even edit anything on it before submitting a second time.

**Comment by Emmyn5600** [comment]
I see you have Books folder in locally, however you have pushed books in the GitHub.

**Comment by sheylaPozo** [comment]
> I see you have Books folder in locally, however you have pushed books in the GitHub.

If it was only locally it would have a notification on the third icon next to the right side on "Source control" and I don't have anything else to commit, because this is been already finished 5 hours ago, I only added styles to it, and it's up to date. I think  I can't modify something that's already functional, because it doesn't work on your end when it works in general, also for the other TSEs that saw it.

**Comment by sheylaPozo** [comment]
> I see you have Books folder in locally, however you have pushed books in the GitHub.
 Something must of happen that it didn't push as Books, I will see if there's any way it can get replaced since on my end it's already been written correctly from many hours ago.

**Comment by sheylaPozo** [comment]
> I see you have Books folder in locally, however you have pushed books in the GitHub.

ok, so I pushed the project again just adding a space and removing it on a random file and let's see if this time it shows a it is for me locally.

**Comment by sheylaPozo** [comment]
> Not, It's styling branch
> syle

I pushed branch changes, hopefully, this time you can run the project without complications, it's kind of close to the hour where they close submissions.

**Review by Emmyn5600 — APPROVED** [review]
Hi,

Good job so far! 👏🏼 @sheylaPozo  

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You have a descriptive Readme file:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.
 
 #### Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by sheylaPozo** [comment]
I believe previous reviewers didn't have a problem with it because previously it was called **books** in the other branch and books in import too, or they wouldn't have been able to run the project either. However I completed the tasks you asked me to do, and now it shows, so thanks for the patience :)

**Pull request merged**
